const data = [
  {
    id: 2001,
    name: "John Smith",
    img: "/avatar1.jpg",
    designation: "Senior Software Engineer",
    country: "USA",
    hireDate: "12/05/2018",
    reportsTo: "Alice",
    employeeID: "005",
  },
  {
    id: 2002,
    name: "Alice Johnson",
    img: "/avatar2.jpg",
    designation: "Product Manager",
    country: "Canada",
    hireDate: "23/09/2016",
    reportsTo: "Bob",
    employeeID: "018",
  },
  {
    id: 2003,
    name: "Bob Davis",
    img: "/avatar3.jpg",
    designation: "QA Engineer",
    country: "Germany",
    hireDate: "05/11/2019",
    reportsTo: "Eva",
    employeeID: "042",
  },
  {
    id: 2004,
    name: "Eva Wilson",
    img: "/avatar4.jpg",
    designation: "UX/UI Designer",
    country: "France",
    hireDate: "17/03/2017",
    reportsTo: "Charlie",
    employeeID: "075",
  },
  {
    id: 2005,
    name: "Charlie Brown",
    img: "/avatar5.jpg",
    designation: "Data Scientist",
    country: "Australia",
    hireDate: "08/08/2020",
    reportsTo: "Diana",
    employeeID: "093",
  },
  {
    id: 2006,
    name: "Diana Miller",
    img: "/avatar6.jpg",
    designation: "System Architect",
    country: "Italy",
    hireDate: "29/01/2015",
    reportsTo: "Frank",
    employeeID: "027",
  },
  {
    id: 2007,
    name: "Frank Davis",
    img: "/avatar1.jpg",
    designation: "DevOps Engineer",
    country: "Brazil",
    hireDate: "12/06/2016",
    reportsTo: "Grace",
    employeeID: "064",
  },
  {
    id: 2008,
    name: "Grace Taylor",
    img: "/avatar2.jpg",
    designation: "Network Engineer",
    country: "Japan",
    hireDate: "03/04/2018",
    reportsTo: "Harry",
    employeeID: "091",
  },
  {
    id: 2009,
    name: "Harry Thomas",
    img: "/avatar3.jpg",
    designation: "Database Administrator",
    country: "South Africa",
    hireDate: "14/10/2019",
    reportsTo: "Ivy",
    employeeID: "037",
  },
  {
    id: 2010,
    name: "Ivy Anderson",
    img: "/avatar4.jpg",
    designation: "Security Analyst",
    country: "South Korea",
    hireDate: "25/12/2015",
    reportsTo: "Jack",
    employeeID: "083",
  },
  {
    id: 2011,
    name: "Jack White",
    img: "/avatar5.jpg",
    designation: "Software Engineer",
    country: "United Kingdom",
    hireDate: "19/09/2018",
    reportsTo: "Kim",
    employeeID: "052",
  },
  {
    id: 2012,
    name: "Kim Lee",
    img: "/avatar6.jpg",
    designation: "Machine Learning Engineer",
    country: "Germany",
    hireDate: "08/05/2016",
    reportsTo: "Lily",
    employeeID: "018",
  },
  {
    id: 2013,
    name: "Lily Brown",
    img: "/avatar1.jpg",
    designation: "Product Manager",
    country: "Canada",
    hireDate: "21/02/2017",
    reportsTo: "Mike",
    employeeID: "046",
  },
  {
    id: 2014,
    name: "Mike Johnson",
    img: "/avatar2.jpg",
    designation: "Quality Assurance Analyst",
    country: "Netherlands",
    hireDate: "10/11/2019",
    reportsTo: "Nina",
    employeeID: "081",
  },
  {
    id: 2015,
    name: "Nina Wilson",
    img: "/avatar3.jpg",
    designation: "Frontend Developer",
    country: "Argentina",
    hireDate: "02/07/2015",
    reportsTo: "Oscar",
    employeeID: "028",
  },
];

export default data;
