const data = [
  {
    id: 1001,
    customerName: "John Doe",
    customerImg: "/avatar1.jpg",
    customerEmail: "john@gmail.com",
    projectName: "Enterprise Resource Implementation",
    status: "Pending",
    weeks: 20,
    budget: "$16.5k",
    location: "New York",
    customerId: 1001,
  },
  {
    id: 1002,
    customerName: "Alice Smith",
    customerImg: "/avatar2.jpg",
    customerEmail: "alice@gmail.com",
    projectName: "Blockchain-based Chain",
    status: "Active",
    weeks: 30,
    budget: "$12.3k",
    location: "Tokyo",
    customerId: 1002,
  },
  {
    id: 1003,
    customerName: "Bob Brown",
    customerImg: "/avatar3.jpg",
    customerEmail: "bob@gmail.com",
    projectName: "Artificial Analytics",
    status: "Complete",
    weeks: 25,
    budget: "$8.7k",
    location: "Paris",
    customerId: 1003,
  },
  {
    id: 1004,
    customerName: "Eva Johnson",
    customerImg: "/avatar4.jpg",
    customerEmail: "eva@gmail.com",
    projectName: "Augmented Reality Showroom",
    status: "Pending",
    weeks: 35,
    budget: "$15.2k",
    location: "London",
    customerId: 1004,
  },
  {
    id: 1005,
    customerName: "Charlie Wilson",
    customerImg: "/avatar5.jpg",
    customerEmail: "charlie@gmail.com",
    projectName: "Deep Image Recognition",
    status: "Cancel",
    weeks: 18,
    budget: "$9.5k",
    location: "New York",
    customerId: 1005,
  },
  {
    id: 1006,
    customerName: "Diana Miller",
    customerImg: "/avatar6.jpg",
    customerEmail: "diana@gmail.com",
    projectName: "Genomic Data Analysis",
    status: "Active",
    weeks: 40,
    budget: "$20.0k",
    location: "Los Angeles",
    customerId: 1006,
  },
  {
    id: 1007,
    customerName: "Frank Davis",
    customerImg: "/avatar1.jpg",
    customerEmail: "frank@gmail.com",
    projectName: "Autonomous Drone System",
    status: "Complete",
    weeks: 22,
    budget: "$13.8k",
    location: "Miami",
    customerId: 1007,
  },
  {
    id: 1008,
    customerName: "Grace Taylor",
    customerImg: "/avatar2.jpg",
    customerEmail: "grace@gmail.com",
    projectName: "Smart City Infrastructure",
    status: "Canceled",
    weeks: 15,
    budget: "$11.1k",
    location: "Sydney",
    customerId: 1008,
  },
  {
    id: 1009,
    customerName: "Harry Thomas",
    customerImg: "/avatar3.jpg",
    customerEmail: "harry@gmail.com",
    projectName: "Quantum Computing Initiative",
    status: "Pending",
    weeks: 28,
    budget: "$18.6k",
    location: "Berlin",
    customerId: 1009,
  },
  {
    id: 1010,
    customerName: "Ivy Anderson",
    customerImg: "/avatar4.jpg",
    customerEmail: "ivy@gmail.com",
    projectName: "Neuroscience-based Enhancement",
    status: "Active",
    weeks: 32,
    budget: "$14.3k",
    location: "Rio de Janeiro",
    customerId: 1010,
  },
  {
    id: 1011,
    customerName: "Jack White",
    customerImg: "/avatar5.jpg",
    customerEmail: "jack@gmail.com",
    projectName: "Quantum Cryptography Network",
    status: "Active",
    weeks: 30,
    budget: "$15.8k",
    location: "Seoul",
    customerId: 1011,
  },
  {
    id: 1012,
    customerName: "Kim Lee",
    customerImg: "/avatar6.jpg",
    customerEmail: "kim.lee@gmail.com",
    projectName: "Biometric Identity System",
    status: "Pending",
    weeks: 28,
    budget: "$12.4k",
    location: "Beijing",
    customerId: 1012,
  },
  {
    id: 1013,
    customerName: "Lily Brown",
    customerImg: "/avatar1.jpg",
    customerEmail: "lily@gmail.com",
    projectName: "Virtual Reality Experience",
    status: "Complete",
    weeks: 20,
    budget: "$9.9k",
    location: "Cape Town",
    customerId: 1013,
  },
  {
    id: 1014,
    customerName: "Mike Johnson",
    customerImg: "/avatar2.jpg",
    customerEmail: "mike@gmail.com",
    projectName: "AI-driven Platform",
    status: "Active",
    weeks: 35,
    budget: "$18.7k",
    location: "Mumbai",
    customerId: 1014,
  },
  {
    id: 1015,
    customerName: "Nina Wilson",
    customerImg: "/avatar3.jpg",
    customerEmail: "nina@gmail.com",
    projectName: "Sustainable Agriculture",
    status: "Canceled",
    weeks: 15,
    budget: "$6.5k",
    location: "Buenos Aires",
    customerId: 1015,
  },
  {
    id: 1016,
    customerName: "Oscar Davis",
    customerImg: "/avatar4.jpg",
    customerEmail: "oscar@gmail.com",
    projectName: "Robotics-based STEM",
    status: "Pending",
    weeks: 25,
    budget: "$14.0k",
    location: "Toronto",
    customerId: 1016,
  },
  {
    id: 1017,
    customerName: "Pam Taylor",
    customerImg: "/avatar5.jpg",
    customerEmail: "pam@gmail.com",
    projectName: "Eco-friendly Fashion",
    status: "Cancel",
    weeks: 18,
    budget: "$11.3k",
    location: "Dubai",
    customerId: 1017,
  },
  {
    id: 1018,
    customerName: "Quinn Thomas",
    customerImg: "/avatar6.jpg",
    customerEmail: "quinn@gmail.com",
    projectName: "Automated Smart Home",
    status: "Complete",
    weeks: 22,
    budget: "$16.5k",
    location: "Rome",
    customerId: 1018,
  },
];

export default data;
