const data = [
  {
    id: 1,
    img: "img1",
    item: "Mango Smoothie",
    customerName: "John",
    totalAmount: 13.99,
    status: "Pending",
    orderId: 358291,
    location: "New York",
  },
  {
    id: 2,
    img: "img2",
    item: "Wireless Earbuds",
    customerName: "Alice",
    totalAmount: 124.5,
    status: "Active",
    orderId: 67218,
    location: "Amsterdam",
  },
  {
    id: 3,
    img: "img3",
    item: "Coffee Maker",
    customerName: "Bob",
    totalAmount: 48.75,
    status: "Complete",
    orderId: 502934,
    location: "Moscow",
  },
  {
    id: 4,
    img: "img4",
    item: "Leather Wallet",
    customerName: "Charlie",
    totalAmount: 245.99,
    status: "Pending",
    orderId: 14578,
    location: "Paris",
  },
  {
    id: 5,
    img: "img5",
    item: "Portable Charger",
    customerName: "Eva",
    totalAmount: 132.0,
    status: "Canceled",
    orderId: 789652,
    location: "Tokyo",
  },
  {
    id: 6,
    img: "img6",
    item: "Travel Pillow",
    customerName: "David",
    totalAmount: 19.99,
    status: "Rejected",
    orderId: 1234567,
    location: "London",
  },
  {
    id: 7,
    img: "img7",
    item: "Power Bank",
    customerName: "Sophia",
    totalAmount: 56.75,
    status: "Active",
    orderId: 98765432,
    location: "Berlin",
  },
  {
    id: 8,
    img: "img8",
    item: "Running Shoes",
    customerName: "John",
    totalAmount: 111.49,
    status: "Complete",
    orderId: 65789,
    location: "Barcelona",
  },
  {
    id: 9,
    img: "img9",
    item: "Smartwatch",
    customerName: "Alice",
    totalAmount: 88.95,
    status: "Pending",
    orderId: 234567,
    location: "Sydney",
  },
  {
    id: 10,
    img: "img10",
    item: "Digital Camera",
    customerName: "Bob",
    totalAmount: 246.99,
    status: "Canceled",
    orderId: 876543,
    location: "Rio de Janeiro",
  },
  {
    id: 11,
    img: "img1",
    item: "Bluetooth Speaker",
    customerName: "Emily",
    totalAmount: 39.99,
    status: "Complete",
    orderId: 123123,
    location: "Los Angeles",
  },
  {
    id: 12,
    img: "img2",
    item: "Power Bank",
    customerName: "Daniel",
    totalAmount: 72.5,
    status: "Active",
    orderId: 456456,
    location: "Berlin",
  },
  {
    id: 13,
    img: "img3",
    item: "Fitness Mat",
    customerName: "Olivia",
    totalAmount: 28.75,
    status: "Pending",
    orderId: 789789,
    location: "Sydney",
  },
  {
    id: 14,
    img: "img4",
    item: "Wireless Mouse",
    customerName: "Michael",
    totalAmount: 15.99,
    status: "Complete",
    orderId: 101010,
    location: "Tokyo",
  },
  {
    id: 15,
    img: "img5",
    item: "Mango Smoothie",
    customerName: "Sophie",
    totalAmount: 19.0,
    status: "Canceled",
    orderId: 121212,
    location: "Paris",
  },
  {
    id: 16,
    img: "img6",
    item: "Digital Camera",
    customerName: "William",
    totalAmount: 12.99,
    status: "Active",
    orderId: 141414,
    location: "New York",
  },
  {
    id: 17,
    img: "img7",
    item: "Travel Pillow",
    customerName: "Emma",
    totalAmount: 8.75,
    status: "Rejected",
    orderId: 161616,
    location: "Amsterdam",
  },
  {
    id: 18,
    img: "img8",
    item: "Wireless Mouse",
    customerName: "Noah",
    totalAmount: 24.49,
    status: "Pending",
    orderId: 181818,
    location: "Moscow",
  },
  {
    id: 19,
    img: "img9",
    item: "Smartwatch",
    customerName: "Ava",
    totalAmount: 99.95,
    status: "Canceled",
    orderId: 202020,
    location: "Barcelona",
  },
  {
    id: 20,
    img: "img10",
    item: "Portable Charger",
    customerName: "Liam",
    totalAmount: 35.75,
    status: "Complete",
    orderId: 222222,
    location: "Rio de Janeiro",
  },
];

export default data;
