const data = [
  {
    id: 1,
    img: "/products/smoothie.png",
    item: "Mango Smoothie",
    customerName: "John",
    totalAmount: 13.99,
    status: "Pending",
    orderId: 358291,
    location: "New York",
  },
  {
    id: 2,
    img: "/products/camera.png",
    item: "Camera",
    customerName: "Alice",
    totalAmount: 26.74,
    status: "Active",
    orderId: 572913,
    location: "Tokyo",
  },
  {
    id: 3,
    img: "/products/candy.png",
    item: "Candy",
    customerName: "Bob",
    totalAmount: 13.45,
    status: "Complete",
    orderId: 89432,
    location: "Paris",
  },
  {
    id: 4,
    img: "/products/charger.png",
    item: "Charger",
    customerName: "Eva",
    totalAmount: 37.21,
    status: "Pending",
    orderId: 671045,
    location: "London",
  },
  {
    id: 5,
    img: "/products/coffee.png",
    item: "Coffee",
    customerName: "Charlie",
    totalAmount: 19.99,
    status: "Rejected",
    orderId: 573952,
    location: "New York",
  },
  {
    id: 6,
    img: "/products/earbuds.png",
    item: "Earbuds",
    customerName: "Diana",
    totalAmount: 42.88,
    status: "Active",
    orderId: 329527,
    location: "Los Angeles",
  },

  {
    id: 7,
    img: "/products/icecream.png",
    item: "Ice Cream",
    customerName: "Frank",
    totalAmount: 15.75,
    status: "Complete",
    orderId: 362953,
    location: "Miami",
  },
  {
    id: 8,
    img: "/products/lamp.png",
    item: "Lamp",
    customerName: "Grace",
    totalAmount: 33.49,
    status: "Canceled",
    orderId: 298725,
    location: "Sydney",
  },
  {
    id: 9,
    img: "/products/pillow.png",
    item: "Pillow",
    customerName: "Harry",
    totalAmount: 29.95,
    status: "Pending",
    orderId: 740275,
    location: "Berlin",
  },
  {
    id: 10,
    img: "/products/pop.png",
    item: "Pop",
    customerName: "Ivy",
    totalAmount: 10.5,
    status: "Active",
    orderId: 740254,
    location: "Rio de Janeiro",
  },
  {
    id: 11,
    img: "/products/powerbank.png",
    item: "Power Bank",
    customerName: "Jack",
    totalAmount: 19.99,
    status: "Rejected",
    orderId: 634204,
    location: "Seoul",
  },
  {
    id: 12,
    img: "/products/shoes.png",
    item: "Shoes",
    customerName: "Kim",
    totalAmount: 54.99,
    status: "Complete",
    orderId: 350892,
    location: "Beijing",
  },
  {
    id: 13,
    img: "/products/smoothie.png",
    item: "Smoothie",
    customerName: "Lily",
    totalAmount: 13.99,
    status: "Pending",
    orderId: 15829,
    location: "Cape Town",
  },
  {
    id: 14,
    img: "/products/spectacles.png",
    item: "Spectacles",
    customerName: "Mike",
    totalAmount: 49.95,
    status: "Active",
    orderId: 24377,
    location: "Mumbai",
  },
  {
    id: 15,
    img: "/products/tomato.png",
    item: "Tomato",
    customerName: "Nina",
    totalAmount: 5.75,
    status: "Canceled",
    orderId: 983643,
    location: "Buenos Aires",
  },
  {
    id: 16,
    img: "/products/toycar.png",
    item: "Toy Car",
    customerName: "Oscar",
    totalAmount: 8.99,
    status: "Pending",
    orderId: 143534,
    location: "Toronto",
  },
  {
    id: 17,
    img: "/products/wallet.png",
    item: "Wallet",
    customerName: "Pam",
    totalAmount: 49.99,
    status: "Rejected",
    orderId: 987882,
    location: "Dubai",
  },
  {
    id: 18,
    img: "/products/watch.png",
    item: "Watch",
    customerName: "Quinn",
    totalAmount: 79.95,
    status: "Complete",
    orderId: 178359,
    location: "Rome",
  },
  {
    id: 19,
    img: "/products/watch2.png",
    item: "Smart Watch ",
    customerName: "Rob",
    totalAmount: 99.99,
    status: "Active",
    orderId: 698230,
    location: "Moscow",
  },
  {
    id: 20,
    img: "/products/camera.png",
    item: "Camera",
    customerName: "Sam",
    totalAmount: 39.99,
    status: "Pending",
    orderId: 176538,
    location: "Barcelona",
  },
];

export default data;
